// <auto-generated />
using System;
using Acceso_Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Acceso_Datos.Migrations
{
    [DbContext(typeof(MyDBcontext))]
    [Migration("20240630052421_Migracion_Modificada")]
    partial class Migracion_Modificada
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entidades.Detalle_Factura", b =>
                {
                    b.Property<int>("IdDetalleFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalleFactura"), 1L, 1);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("IdFacturaEnDetalle")
                        .HasColumnType("int");

                    b.Property<int>("IdProductoEnDetalle")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioDel_Producto")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdDetalleFactura");

                    b.HasIndex("IdFacturaEnDetalle");

                    b.HasIndex("IdProductoEnDetalle");

                    b.ToTable("Detalle_Facturas");
                });

            modelBuilder.Entity("Entidades.Factura", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFactura"), 1L, 1);

                    b.Property<int>("Correlativo")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRealizada")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdFactura");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("Entidades.Producto", b =>
                {
                    b.Property<int>("IdProdructo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProdructo"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdProdructo");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Entidades.Detalle_Factura", b =>
                {
                    b.HasOne("Entidades.Factura", "Objeto_Factura")
                        .WithMany("Lista_DetalleFactura")
                        .HasForeignKey("IdFacturaEnDetalle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entidades.Producto", "Objeto_Producto")
                        .WithMany("Lista_DetalleFactura")
                        .HasForeignKey("IdProductoEnDetalle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Objeto_Factura");

                    b.Navigation("Objeto_Producto");
                });

            modelBuilder.Entity("Entidades.Factura", b =>
                {
                    b.Navigation("Lista_DetalleFactura");
                });

            modelBuilder.Entity("Entidades.Producto", b =>
                {
                    b.Navigation("Lista_DetalleFactura");
                });
#pragma warning restore 612, 618
        }
    }
}
